import { BadgeEnum, OwnerEnum, RankingTypeEnum, TaskFieldEnum, UIEnum, UploadFormatEnum, WorkspaceEnum } from "./enums.util";

export type NA = null | undefined;
export type IconName = '';
export type IconFamilyType = 'polio' | 'fa' | 'feather';
export type FontFamilyType = 'mona' | 'uncut'
export type SizeType = 'xmini' | 'mini' | 'xxsm' | 'xsm' | 'sm' | 'rg' | 'default' | 'md' | 'lg' | 'xlg' | 'xxlg' | 'lgr';
export type SemanticType = 'normal' | 'default' | 'blue' | 'info' | 'yellow' | 'warning' | 'orange' | 'warning-2' | 'green' | 'success' | 'red' | 'error' | 'purple' | 'ongoing' | 'pink';
export type ButtonType = 'primary' | 'secondary' | 'ghost' | 'icon' | 'link'
export type RouteParamType = 'url' | 'query' | 'path';
export type RouteActionType = 'navigate' | 'open-secondary' | 'logout';
export type UserType = 'superadmin' | 'admin' | 'business' | 'talent' | 'user';
export type ApiServiceType = 'default' | 'backend' | 'identity' | 'core' | 'genius' | 'resource';
export type ApiMethodType = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
export type NavItemType = 'sidebar' | 'navbar' | 'topbar';
export type DisabledType = 'default' | 'blind' | 'light' | 'visible';
export type LoadingType = 'default' | 'loader' | 'resource' | 'workspace'
export type QueryOrderType = 'desc' | 'asc'
export type StatusType = 'enabled' | 'active' | 'status'
export type PositionType = 'default' | 'top' | 'top-left' | 'top-right' | 'top-center' | 'bottom' | 'bottom-left' | 'bottom-right' | 'bottom-center' | 'left' | 'right'
export type LevelType = 'default' | 'novice' | 'beginner' | 'intermediate' | 'advanced' | 'professional'
export type DifficultyType = 'random' | 'easy' | 'normal' | 'hard' | 'difficult'
export type QuestionType = 'trivial' | 'career' | 'general'
export type RubricType = 'level' | 'question-type' | 'difficulty' | 'score' | 'time'
export type FlexReverseType = 'row' | 'column' | 'default' | 'wrap';
export type FontWeightType = 100 | 'thin' | 200 | 'xlight' | 300 | 'light' | 400 | 'regular' | 500 | 'medium' | 600 | 'semibold' | 700 | 'bold' | 800 | 'xbold' | 900 | 'black' | 'heavy'; 
export type FormActionType = 'edit-resource' | 'add-resource';
export type UIDisplayType = 'list' | 'table' | 'single' | 'details';
export type FileAcceptType = 'csv' | 'sheet' | 'pdf' | 'image' | 'video' | 'audo';
export type CSVAcceptType = '.csv' | '.xls' | 'application/vnd.ms-excel' | 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
export type TextAcceptType = 'text/plain' | 'text/html'
export type VideoAcceptType = 'video/*'
export type AudioAcceptType = 'audio/*'
export type DocAcceptType = 'application/msword' | 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' | '.docx';
export type UploadAcceptType = Array<CSVAcceptType | ImageAcceptType | PDFAcceptType | VideoAcceptType | AudioAcceptType>;
export type PDFAcceptType = '.pdf' | 'application/pdf'
export type ImageAcceptType = 'image/x-png' | 'image/jpg' | 'image/jpeg' | 'image/png' | 'image/svg' | 'image/gif' | 'image/*' | 'image/x-eps'
export type ResourceType = 'default' | 'leaderboard' | 'user' | 'users' | 'industry' | 'industries' | 'career' | 'careers' | 'field' | 'fields' | 
'skill' | 'skills' | 'topic' | 'topics' | 'question' | 'questions' | 'assessments' | 'assessment' | 'roadmaps' | 'roadmap' | 'tasks'
export type ListUIType = 'self' | 'resource' | 'details';
export type FilterType = 'default' | 'assessments' | 'user' | 'industry' | 'career' | 'field' | 'skill' | 'topic' | 'question' | 'roadmap' | 'talent' | 'talents'
export type PagesearchType = 'search' | 'filter'
export type FormatDateType = 'basic' | 'basic-month' | 'basic-bare' | 'calendar-format' | 'datetime' | 'datetime-slash' | 'datetime-separated' | 'separated' | 'localtime' | 'slashed'
export type RefineType = 'default' | 'search' | 'filter';
export type ChoiceCheckType = 'correct' | 'not-correct' | 'not-existing';
export type FeatureCategory = 'base' | 'addon'
export type RankingType = typeof RankingTypeEnum[keyof typeof RankingTypeEnum]
export type BadgeType = typeof BadgeEnum[keyof typeof BadgeEnum]
export type TaskFieldType = typeof TaskFieldEnum[keyof typeof TaskFieldEnum]
export type UIType = typeof UIEnum[keyof typeof UIEnum]
export type WorkspaceType = typeof WorkspaceEnum[keyof typeof WorkspaceEnum]
export type OwnerType = typeof OwnerEnum[keyof typeof OwnerEnum]
export type UploadFormat = typeof UploadFormatEnum[keyof typeof UploadFormatEnum]
